# Generated by Django 2.2.1 on 2019-05-16 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Patients',
                'verbose_name': 'Patient',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, null=True, unique=True)),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Tenants',
                'verbose_name': 'Tenant',
            },
        ),
        migrations.CreateModel(
            name='ScheduledService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_ten.Patient', verbose_name='Patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_ten.Tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name_plural': 'Scheduled Services',
                'verbose_name': 'Scheduled Service',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='tenant',
            field=models.ManyToManyField(to='test_ten.Tenant', verbose_name='Tenant'),
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BooleanField(default=False, verbose_name='Owner')),
                ('_is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_ten.Tenant', verbose_name='Tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Collaborations',
                'unique_together': {('tenant', 'user')},
                'verbose_name': 'Collaboration',
            },
        ),
    ]
